services:
  backend:
    build: ./backend
    container_name: cveraptor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: nginx:alpine
    container_name: cveraptor-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend